### ISSUE TITLE
Very CPU intersive to convert RGBA every time

### ISSUE THREAD

**Issue by Lewiscowles1986** [gabrielrcouto/php-terminal-gameboy-emulator#14]
Simply put, don't convert every time, one-time or over multiple iterations build an array, or object you can use to lookup values, it's going to be so much easier than computing anything to simply serialize the results somewhere, even if it's done at runtime costing RAM (assuming the GBA has 65536 colours or something insane like that).

**Comment by oo-00** [comment]
I know it's been over 4 years, but for anyone else reading, I just want to add: I added usleep(1000) ; below $this->untilEnable--; in core.php, and it seems to have cut CPU usage in half without affecting gameplay. - and that's with it modified for SDL video support instead of console.

**Comment by Lewiscowles1986** [comment]
Think we can close then? I'll close for now. Re-open if you think it's still valid.
