### ISSUE TITLE
ROM Files

### ISSUE THREAD

**Issue by Lewiscowles1986** [gabrielrcouto/php-terminal-gameboy-emulator#15]
Github is not the best place to store arbitrary binary files, especially not ones like Dr Mario, which may be violating copyright. I Know there are other sites, simply say get your own roms, and leave it at that.

**Comment by gabrielrcouto** [comment]
Thank you, we are working on that: https://github.com/gabrielrcouto/php-terminal-gameboy-emulator/pull/8
