### ISSUE TITLE
Copyrighted roms still exist in repository history

### ISSUE THREAD

**Issue by ikari7789** [gabrielrcouto/php-terminal-gameboy-emulator#25]
The copyrighted roms still exist in the commit history. The GBA boot rom was removed properly, but the rom data still exists. Need to use bfg on the three roms and re-upload the repository.

**Comment by gabrielrcouto** [comment]
Done

**Comment by ikari7789** [comment]
Good stuff! Less reason now for Nintendo to come breathing down your throat :)
