### ISSUE TITLE
[Proposal] Running emulator inside a symfony application container

### ISSUE THREAD

**Issue by mauri870** [gabrielrcouto/php-terminal-gameboy-emulator#27]
The symfony container providing a interface for handle with commands easy and functional, no changes on core must be made, the wrapper of the application will be changed

**Comment by henriquemoody** [comment]
If you're talking about _Symfony\Console_ I think it's not necessary.

IMO, this command line too simple for that. There is just one command with just one argument. In the future, if more options or features come, then I think it's a good idea.

Again, IMO...

**Comment by mauri870** [comment]
:+1:

**Comment by reisraff** [comment]
In future if more options or features come, this should be an option:

https://github.com/wp-cli/php-cli-tools

**Comment by reisraff** [comment]
See #34 PR

**Comment by gabrielrcouto** [comment]
I think the main idea of an emulator is to just run a game. I like the symfony/console, but will we need more commands than "play"?
I only see the need for parameters, and we can do that without symfony/console.
What about a nice intro made in ASCII, like the GameBoy boot? And a file navigator, using the checkbox from CLImate?
Let's do something out of the box, this project is to do crazy and nice things, and to push PHP to new levels.
