### ISSUE TITLE
I'm so sorry

### ISSUE THREAD

**Issue by taisel** [gabrielrcouto/php-terminal-gameboy-emulator#31]
That you had to deal with a monolithic god object. It was designed that way as a workaround for shitty browsers in the JavaScript version circa 2010.

**Comment by gabrielrcouto** [comment]
Wow, it's an honour to have your comment here! Really, you dont need to say sorry, you did a very great job, and I will be thankful forever! I used your emulator in 2010, and was so much amazing that on 2016 I used as my inspiration (and base). Thank you so much! 😀

**Comment by taisel** [comment]
I'm just wondering how you managed to grab an out of date copy, since it hasn't been updated in forever. ._.
