### ISSUE TITLE
Upload PHAR archive

### ISSUE THREAD

**Issue by henriquemoody** [gabrielrcouto/php-terminal-gameboy-emulator#33]
On the _Downloads_ section of [a release](https://github.com/gabrielrcouto/php-terminal-gameboy-emulator/releases/tag/0.1.0) would be nice if you upload the PHAR archive.

**Comment by reisraff** [comment]
use the gh-pages branch for it.

**Comment by gabrielrcouto** [comment]
How we can automate it?

**Comment by henriquemoody** [comment]
Something similar to that: https://medium.com/@nthgergo/publishing-gh-pages-with-travis-ci-53a8270e87db#.wg8tq44d7

**Comment by henriquemoody** [comment]
Probably not relevant anymore. I'm gonna close this one :)
