### ISSUE TITLE
Keypress is shown on terminal

### ISSUE THREAD

**Issue by reisraff** [gabrielrcouto/php-terminal-gameboy-emulator#35]
As you can see int the following image

![image](http://i.imgur.com/kxs5TF9.png?1)

**Comment by gabrielrcouto** [comment]
Yes, you're right. Can we disable this using something like @ECHO OFF?

**Comment by reenl** [comment]
Symfony has code for hidden input:
https://github.com/symfony/console/blob/master/Helper/QuestionHelper.php#L323

I'd PR something if I had the time

**Comment by toverux** [comment]
Yes, `stty -echo` (used in the Symfony source code above) is the best way I know to disable local echo, and is very portable (Unix family). Safe to use :)

**Comment by petriuslima** [comment]
Is there a default key to stop the game? I'm using `ctrl + c` for now but after the addition of `stty -echo` i'm having to execute `stty echo` to show my input on terminal again.
Sorry if it's a stupid question.

**Comment by reisraff** [comment]
Humm so we need then set the `stty echo` on the `register_shutdown_function`

**Comment by reisraff** [comment]
something like:

``` php
<?php
function shutdown()
{
    exec('stty echo');
}

register_shutdown_function('shutdown'); 
```

**Comment by petriuslima** [comment]
Sorry, I didn't explain the problem correctly. 
I was using php 5.6.18 in a vagrant box with ubuntu 12.04 when the problem occurred. But in another vagrant box with ubuntu 14.04 and php 7.0.3 (and also tested with php 5.6.18) this problem not occur.
I don't know why, but as the emulator works just changing the distro. I think that it's a  problem with S.O.. how to proceed about this?
