### ISSUE TITLE
"'stty' is not recognized as an internal or external command, operable program or batch file." when running on windows (Either MinGW and Windows CMD)

### ISSUE THREAD

**Issue by ricardofiorani** [gabrielrcouto/php-terminal-gameboy-emulator#36]
When running under windows I get stty is not recongnized error.

Raw Output : 

C:\wamp\www\php-terminal-gameboy-emulator>php boot.php pokemon.rom
'stty' is not recognized as an internal or external command,
operable program or batch file.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
 64 bytes) in C:\wamp\www\php-terminal-gameboy-emulator\src\GameBoy\Core.php on
line 2809

Call Stack:
    0.0010     235568   1. {main}() C:\wamp\www\php-terminal-gameboy-emulator\bo
ot.php:0
    0.0310    6304760   2. GameBoy\Core->start() C:\wamp\www\php-terminal-gamebo
y-emulator\boot.php:19
    0.0360   14257776   3. GameBoy\Core->ROMLoad() C:\wamp\www\php-terminal-game
boy-emulator\src\GameBoy\Core.php:641
    0.0360   14257952   4. GameBoy\Core->getTypedArray() C:\wamp\www\php-termina
l-gameboy-emulator\src\GameBoy\Core.php:734
    0.0360   14258048   5. array_fill() C:\wamp\www\php-terminal-gameboy-emulato
r\src\GameBoy\Core.php:2809

**Comment by ricardofiorani** [comment]
This error occurs on all PHP versions that I tested.
- PHP 5.5 (bypassing composer php version)
- PHP 5.6
- PHP 7

**Comment by gabrielrcouto** [comment]
The fatal error is about memory (and yes, the stty is not suposed to work on Windows), you need to change the memory_limit as suggested on issue #4.
A Windows user said me that the emulator runs fine on PowerShell, but without stty, the inputs only work after pressing enter.
