### ISSUE TITLE
Memory size

### ISSUE THREAD

**Issue by Hartaxfr** [gabrielrcouto/php-terminal-gameboy-emulator#4]
I use Babun and when i run pokemon.rom i get this error : 

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 24 bytes) in /cygdrive/c/Users/averry/Documents/php-terminal-gameboy-emulator-master/src/GameBoy/Core.php on line 740

**Comment by jcambien** [comment]
@Hartaxfr Your PHP memory limit setting is low.

try this :
`php -d "memory_limit=512M" boot.php pokemon.rom`

**Comment by emielmolenaar** [comment]
Or try PHP 7, if you already haven't. PHP 7 should consume less memory.

**Comment by Hartaxfr** [comment]
it works ! 

> @Hartaxfr Your PHP memory limit setting is low.
> 
> try this :
> `php -d "memory_limit=512M" boot.php pokemon.rom`
