### ISSUE TITLE
-bash: php-gameboy: command not found

### ISSUE THREAD

**Issue by ghost** [gabrielrcouto/php-terminal-gameboy-emulator#43]
I'm new to PHP, saw this project on lifehacker and wanted to try it out. I installed composer, upgraded PHP to 7.0.4, followed all of the instructions in the readme and keep getting: "-bash: php-gameboy: command not found". 

I'm guessing I have to edit my BASH profile to get the command to work, but I'm not sure how to do that, or if I'm leaving out an important step?

**Comment by mattdinthehouse** [comment]
The directory that php-gameboy is located isn't in your PATH environment variable. You either need to add the directory or enter the absolute filepath to it eg: /path/to/php-gameboy.

**Comment by petriuslima** [comment]
@estherzinn I think that this can also occur if you don't give the permissions to execute the file (`chmod +x php-gameboy.phar`).
